# Generated by Django 4.2.4 on 2023-12-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=128)),
                ("password", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("role", models.CharField(max_length=128)),
            ],
        ),
    ]
