# Generated by Django 4.2.4 on 2024-01-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ChabokJobWebsite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboffer",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_offer",
                to="ChabokJobWebsite.user",
            ),
        ),
    ]
