# Generated by Django 4.2.9 on 2024-01-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ChabokJobWebsite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="salary",
            field=models.IntegerField(null=True),
        ),
    ]
