# Generated by Django 4.2.4 on 2024-01-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ChabokJobWebsite", "0002_joboffer_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
