# Generated by Django 4.2.4 on 2024-01-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ChabokJobWebsite", "0002_alter_user_age_alter_user_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(blank=True, default=21, null=True),
        ),
    ]
